### ISSUE TITLE
HUBOT_PAGERDUTY_SERVICES seems to not work 

### ISSUE THREAD

**Issue by auduny** [hubot-scripts/hubot-pager-me#109]
Hi. 

I've added HUBOT_PAGERDUTY_SERVICES to limit hubot to report on only one service

But "who's on call?" still returns all on-call schedules? Is that intentional?

**Comment by eldios** [comment]
any news on this? I'm having the same behavior almost a year later.

**Comment by stephenyeargin** [comment]
Schedule call lands here:

https://github.com/hubot-scripts/hubot-pager-me/blob/75fbe3060cf92bd2421f18c1ed2f06f9dd7186c1/src/pagerduty.coffee#L132-L142

Which supposedly appends a query string here:

https://github.com/hubot-scripts/hubot-pager-me/blob/75fbe3060cf92bd2421f18c1ed2f06f9dd7186c1/src/pagerduty.coffee#L36-L37

That last bit may not match the on-call endpoint, so that's what would need to be adjusted. I do not have a PagerDuty account any longer, but that should get somebody going in the right direction.

**Comment by eldios** [comment]
Is seems that the problem is that the check on line 36 is checking for incident while the `who's on call` command uses the `/schedules` link. One further level of problem is that the HUBOT_PAGERDUTY_SERVICES is specifying "services" as the name implies, so a further check would be needed in order to understand what "schedules" to query.

**Comment by eldios** [comment]
Trying to propose a different approach here with a little addition:

https://github.com/hubot-scripts/hubot-pager-me/pull/117

**Comment by eldios** [comment]
@stephenyeargin could you please take a look? If that's a reasonable feature we may work on expanding the same approach to all the other commands.

**Comment by stephenyeargin** [comment]
Yep, I think this would be fine. Thanks for working on it. Left a request for some documentation updates.

**Comment by stephenyeargin** [comment]
Closed via #117
