### ISSUE TITLE
Feature Request: Enable Service to Room map so specific teams can handle issues for specific services

### ISSUE THREAD

**Issue by mtscout6** [hubot-scripts/hubot-pager-me#76]
We have numerous development teams that we would like to integrate PagerDuty with. It seems as though using this plugin would allow us to have more support staff deal with issues without the Full PagerDuty experience.

Unfortunately due to the number of services we need to monitor it would be ideal if these services could be announced in different rooms. Is that a feature that would have merit with you?

**Comment by stephenyeargin** [comment]
I'm guessing that you are using the [webhook callback](https://github.com/hubot-scripts/hubot-pager-me#webhook), correct? How would you like to go about mapping services to rooms via the environment variables? (e.g. `HUBOT_PAGERDUTY_ROOM=<service_id>:<room>,<service_id>:<room>`)

Full disclaimer: I don't have a lot of experience with the incoming Webhook because we are using the [native Slack integration](https://slack.com/apps/A0F81FMQW-pagerduty) for alerting. We then use `hubot-pager-me` to handle `ack` and `resolve` operations, as well as getting schedules. But we do accomplish a goal similar to what you're describing by routing our services to a particular channel, such as:

![screen shot 2015-12-22 at 12 05 03 pm](https://cloud.githubusercontent.com/assets/80459/11962281/449716d4-a8a4-11e5-84e0-638b52690416.png)

That doesn't fit your desired outcome, but that was our workaround for a similar problem.

**Comment by mtscout6** [comment]
We were thinking about using the Webhook callback, but what you are describing sounds a lot simpler. I guess this wouldn't be needed in that case. We use HipChat, and there is an integration for Pager duty there.

**Comment by mtscout6** [comment]
I'm going to close this in favor of what you proposed. Thanks for the tip!

**Comment by technicalpickles** [comment]
I have considered something along these lines too. That is, updating `pager sup|ack|resolve` so they only affect services relevant to the room you are calling them in.
